name: helm-upgrade
run-name: ${{ github.actor }} - ${{ github.ref_name }}
on:
  workflow_call:
    inputs:
      environment:
        required: true
        description:  'environment to deploy to'
        type: string
      version:
        required: true
        type: string
      helm-values-path:
        type: string
        default: './todoapp/values.yaml'

jobs:
  deploy-helm:
    runs-on: ubuntu-latest
    name: ${{ inputs.environment }}
    environment: ${{ inputs.environment }}

    steps:
      - uses: actions/download-artifact@v4
        with:
          name: helm-package
          path: .

      - uses: actions/download-artifact@v4
        with:
          name: helm-artifacts
          path: .

      - name: Download cluster config artifact
        uses: actions/download-artifact@v4
        with:
          name: cluster-config
          path: .

      - name: Create k8s kind cluster
        uses: helm/kind-action@v1
        with:
          config: cluster.yml

      - name: Set up Helm
        uses: azure/setup-helm@v4.2.0

      - name: Deploy Helm to ${{ inputs.environment }}
        run: |
          helm upgrade --install --atomic --wait --timeout 3600s --debug todoapp ./todoapp-*.tgz \
          -f ${{ inputs.helm-values-path }} \
          --set mysql.secrets.MYSQL_ROOT_PASSWORD="${{ secrets.MYSQL_ROOT_PASSWORD }}" \
          --set mysql.secrets.MYSQL_USER="${{ secrets.MYSQL_USER }}" \
          --set mysql.secrets.MYSQL_PASSWORD="${{ secrets.MYSQL_PASSWORD }}" \
          --set todoapp.secrets.SECRET_KEY="${{ secrets.SECRET_KEY }}" \
          --set todoapp.secrets.DB_NAME="${{ secrets.DB_NAME }}" \
          --set todoapp.secrets.DB_USER="${{ secrets.DB_USER }}" \
          --set todoapp.secrets.DB_PASSWORD="${{ secrets.DB_PASSWORD }}" \
          --set todoapp.secrets.DB_HOST="${{ secrets.DB_HOST }}" \
          --set todoapp.image.version="${{ inputs.version }}"

